package laboratoriofm2.pkg0;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.demo.DateChooserPanel;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

public class Rentas extends javax.swing.JInternalFrame {

    String memoria1, memoria2, memoria3, respuesta;

    /**
     * Creates new form Rentas
     */
    public Rentas() {
        initComponents();
        comboDB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtbuscado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbx_CodigoA = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbx_Tarjeta = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        txtMora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtFecha_Renta = new com.toedter.calendar.JDateChooser();
        dtFecha_Entrega = new com.toedter.calendar.JDateChooser();
        cmbx_Tienda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Rentas");
        setVisible(true);

        jLabel10.setText("Mora:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo de artículo:");

        jLabel8.setText("Cantidad:");

        cmbx_CodigoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_CodigoAActionPerformed(evt);
            }
        });

        jLabel4.setText("Número de tarjeta:");

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio:");

        jLabel6.setText("Total:");

        cmbx_Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_TarjetaActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha de renta");

        jLabel2.setText("Fecha de entrega");

        dtFecha_Renta.setDateFormatString("yyyy-MM-dd H:mm");

        dtFecha_Entrega.setDateFormatString("yyyy-MM-dd H:mm");

        cmbx_Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_TiendaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tienda:");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dtFecha_Entrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dtFecha_Renta, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnModificar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbx_Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbx_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbx_CodigoA, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMora, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(btCalcular))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(75, 75, 75)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbx_Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbx_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbx_CodigoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalcular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dtFecha_Renta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dtFecha_Entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnRegistrar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void comboDB() {
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "6182");

            PreparedStatement pst = cn.prepareStatement("select Tarjeta_C from Clientes");
            ResultSet rs = pst.executeQuery();

            PreparedStatement pst2 = cn.prepareStatement("select Codigo_A from Articulos");
            ResultSet rs2 = pst2.executeQuery();

            PreparedStatement pst3 = cn.prepareStatement("select Codigo_T from Tiendas");
            ResultSet rs3 = pst3.executeQuery();
            cmbx_Tarjeta.addItem("Seleccione una opción");
            while (rs.next()) {
                cmbx_Tarjeta.addItem(rs.getString("Tarjeta_C"));
            }
            cmbx_CodigoA.addItem("Seleccione una opción");
            while (rs2.next()) {
                cmbx_CodigoA.addItem(rs2.getString("Codigo_A"));
            }
            cmbx_Tienda.addItem("Seleccione una opción");
            while (rs3.next()) {
                cmbx_Tienda.addItem(rs3.getString("Codigo_T"));
            }

        } catch (Exception e) {

        }
    }
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        java.util.Date fecha = dtFecha_Renta.getDate();
        long d = fecha.getTime();
        java.sql.Date date = new java.sql.Date(d);

        java.util.Date fecha1 = dtFecha_Entrega.getDate();
        long c = fecha1.getTime();
        java.sql.Date date1 = new java.sql.Date(c);
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "6182");
            PreparedStatement pst = cn.prepareStatement("insert into Rentas Value (?,?,?,?,?,?,?,?,?");

            pst.setString(1, "0");
            pst.setString(2, "1");
            pst.setString(3, "2");
            pst.setString(4, "3");
            pst.setString(5, txtCantidad.getText().trim());
            pst.setString(6, txtMora.getText().trim());
            pst.setString(7, txtTotal.getText().trim());
            pst.setString(8, date.toString());
            pst.setString(9, date1.toString());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "¡REGISTRO EXITOSO!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

            txtCantidad.setText("");
            txtTotal.setText("");
            txtPrecio.setText("");
            txtMora.setText("");
            txtbuscado.setText("");
            cmbx_CodigoA.setSelectedIndex(0);
            cmbx_Tienda.setSelectedIndex(0);
            cmbx_Tarjeta.setSelectedIndex(0);
            dtFecha_Renta.remove(0);
            dtFecha_Entrega.remove(0);

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "¡REGITRO FALLIDO!", "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String buscar = txtbuscado.getText().trim();
        if (buscar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso el campo de busqueda!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        cmbx_CodigoA.removeAllItems();
        cmbx_Tienda.removeAllItems();
        cmbx_Tarjeta.removeAllItems();
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "6182");
            PreparedStatement pst = cn.prepareStatement("select * from Rentas where Codigo_R = ? ");
            pst.setString(1, txtbuscado.getText().trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cmbx_Tienda.addItem(rs.getString("Codigo_T"));
                cmbx_Tarjeta.addItem(rs.getString("Tarjeta_C"));
                cmbx_CodigoA.addItem(rs.getString("Codigo_A"));
                txtCantidad.setText(rs.getString("Cantidad_A"));
                txtTotal.setText(rs.getString("Total_R"));
                txtMora.setText(rs.getString("Mora"));
                dtFecha_Renta.setDateFormatString(rs.getString("Fecha_Inico"));
                dtFecha_Entrega.setDateFormatString(rs.getString("Fecha_Vencimiento"));
                txtPrecio.setText(rs.getString("Precio_A"));
                btnEliminar.setEnabled(true);
                btnModificar.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(null, "Renta no registrada.");
            }

        } catch (HeadlessException | SQLException e) {

        }
          try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "6182");
            PreparedStatement pst = cn.prepareStatement("select Precio_A from Articulos where Codigo_A= ?");
            pst.setString(1, cmbx_CodigoA.getSelectedItem().toString());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {

                txtPrecio.setText(rs.getString("Precio_A"));
            } else {

            }
        } catch (SQLException e) {

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbx_CodigoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_CodigoAActionPerformed

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "6182");
            PreparedStatement pst = cn.prepareStatement("select Precio_A from Articulos where Codigo_A= ?");
            pst.setString(1, cmbx_CodigoA.getSelectedItem().toString());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {

                txtPrecio.setText(rs.getString("Precio_A"));
            } else {

            }
        } catch (SQLException e) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbx_CodigoAActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "6182");
            PreparedStatement pst = cn.prepareStatement("delete from Rentas where Codigo_R = ?");

            pst.setString(1, txtbuscado.getText().trim());
            pst.executeUpdate();

            txtbuscado.setText("");

            JOptionPane.showMessageDialog(this, "REGISTRO ELIMINADO.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);

            txtCantidad.setText("");
            txtTotal.setText("");
            txtPrecio.setText("");
            txtMora.setText("");
            txtbuscado.setText("");
            cmbx_CodigoA.setSelectedIndex(0);
            cmbx_Tienda.setSelectedIndex(0);
            cmbx_Tarjeta.setSelectedIndex(0);
            dtFecha_Renta.remove(0);
            dtFecha_Entrega.remove(0);

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en la eliminación de registros.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            String codigo = txtbuscado.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "6182");
            PreparedStatement pst = cn.prepareStatement("update Rentas set Codigo_T= ? , Tarjeta_C = ? , Codigo_A =? , Cantidad_A= ? , Mora ?, Total_R= ?, Fecha_Inico=?, Fecha_Vencimiento=? where Codigo_R = " + codigo);

            pst.setString(1, cmbx_Tienda.getSelectedItem().toString());
            pst.setString(2, cmbx_Tarjeta.getSelectedItem().toString());
            pst.setString(3, cmbx_CodigoA.getSelectedItem().toString());
            pst.setString(4, txtCantidad.getText().trim());
            pst.setString(5, txtMora.getText().trim());
            pst.setString(6, txtTotal.getText().trim());
            pst.setString(7, dtFecha_Renta.getDateFormatString());
            pst.setString(8, dtFecha_Entrega.getDateFormatString());

            //buscare algo
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "MODIFICACION EXITOSA.", "Exito", JOptionPane.INFORMATION_MESSAGE);

            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);

            txtCantidad.setText("");
            txtTotal.setText("");
            txtPrecio.setText("");
            txtMora.setText("");
            txtbuscado.setText("");
            cmbx_CodigoA.setSelectedIndex(0);
            cmbx_Tienda.setSelectedIndex(0);
            cmbx_Tarjeta.setSelectedIndex(0);
            dtFecha_Renta.remove(0);
            dtFecha_Entrega.remove(0);

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "NO SE PUDO MODIFICAR.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cmbx_TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_TarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbx_TarjetaActionPerformed

    private void cmbx_TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_TiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbx_TiendaActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        String resultado;
        memoria1 = txtPrecio.getText().trim();
        memoria2 = txtCantidad.getText().trim();
        memoria3 = txtMora.getText().trim();
        resultado = calcular(memoria1, memoria2, memoria3);
        txtTotal.setText(resultado);
    }//GEN-LAST:event_btCalcularActionPerformed
    public static String calcular(String memoria1, String memoria2, String memoria3) {
        Double resultado = 0.0;
        String respuesta;
        resultado = Double.parseDouble(memoria1) * Double.parseDouble(memoria2) + Double.parseDouble(memoria3);
        respuesta = resultado.toString();

        return respuesta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbx_CodigoA;
    private javax.swing.JComboBox<String> cmbx_Tarjeta;
    private javax.swing.JComboBox<String> cmbx_Tienda;
    private com.toedter.calendar.JDateChooser dtFecha_Entrega;
    private com.toedter.calendar.JDateChooser dtFecha_Renta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtMora;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
